require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'db/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'app/views/**/**/*.haml'
    - 'docs/**/*'
    - 'setup/*'
  TargetRubyVersion: 3.1

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120
